package atividade2;

import java.text.DecimalFormat;

/**
 * @author Claudemir
 */
public class GastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form GastoCalorico
     */
    public GastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadioButton = new javax.swing.ButtonGroup();
        GastoCalorico = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Calculo = new javax.swing.JPanel();
        rbutMulher = new javax.swing.JRadioButton();
        rbutHomem = new javax.swing.JRadioButton();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        lblNvlAtividade = new javax.swing.JLabel();
        cboxNvlAtividade = new javax.swing.JComboBox<>();
        butCalcular = new javax.swing.JButton();
        Resultado = new javax.swing.JPanel();
        lblGastoBasal = new javax.swing.JLabel();
        lblGastoTotal = new javax.swing.JLabel();
        txtGastoBasal = new javax.swing.JLabel();
        txtGastoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gasto Calórico");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo.setText("Cálculo de Gasto Calórico:");

        Calculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroupRadioButton.add(rbutMulher);
        rbutMulher.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rbutMulher.setText("Mulher");

        buttonGroupRadioButton.add(rbutHomem);
        rbutHomem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rbutHomem.setText("Homem");

        lblPeso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPeso.setText("Peso (kg):");

        lblAltura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAltura.setText("Altura (cm):");

        lblIdade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblIdade.setText("Idade:");

        lblNvlAtividade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNvlAtividade.setText("Nível de Atividade:");

        cboxNvlAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve", "Moderado", "Ativo", "Extremamente Ativo" }));
        cboxNvlAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxNvlAtividadeActionPerformed(evt);
            }
        });

        butCalcular.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        butCalcular.setText("Calcular");
        butCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculoLayout = new javax.swing.GroupLayout(Calculo);
        Calculo.setLayout(CalculoLayout);
        CalculoLayout.setHorizontalGroup(
            CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbutMulher, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(rbutHomem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(CalculoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CalculoLayout.createSequentialGroup()
                        .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPeso)
                            .addComponent(lblAltura))
                        .addGap(87, 87, 87)
                        .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculoLayout.createSequentialGroup()
                        .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdade)
                            .addComponent(lblNvlAtividade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtIdade)
                            .addComponent(cboxNvlAtividade, 0, 134, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        CalculoLayout.setVerticalGroup(
            CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbutMulher)
                    .addComponent(rbutHomem))
                .addGap(18, 18, 18)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNvlAtividade)
                    .addComponent(cboxNvlAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        Resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblGastoBasal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblGastoBasal.setText("Gasto Basal:");

        lblGastoTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblGastoTotal.setText("Gasto Total:");

        txtGastoBasal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtGastoTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout ResultadoLayout = new javax.swing.GroupLayout(Resultado);
        Resultado.setLayout(ResultadoLayout);
        ResultadoLayout.setHorizontalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(lblGastoBasal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGastoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(lblGastoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGastoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        ResultadoLayout.setVerticalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGastoBasal)
                    .addComponent(txtGastoBasal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGastoTotal)
                    .addComponent(txtGastoTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GastoCaloricoLayout = new javax.swing.GroupLayout(GastoCalorico);
        GastoCalorico.setLayout(GastoCaloricoLayout);
        GastoCaloricoLayout.setHorizontalGroup(
            GastoCaloricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GastoCaloricoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(GastoCaloricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Calculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo)
                    .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        GastoCaloricoLayout.setVerticalGroup(
            GastoCaloricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GastoCaloricoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GastoCalorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GastoCalorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalcularActionPerformed
        //RECEBE OS DADOS DIGITADOS
        calculaGastoCal(Double.parseDouble(txtPeso.getText()), 
                Double.parseDouble(txtAltura.getText()),
                Integer.parseInt(txtIdade.getText()));
    }//GEN-LAST:event_butCalcularActionPerformed

    private void cboxNvlAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxNvlAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxNvlAtividadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calculo;
    private javax.swing.JPanel GastoCalorico;
    private javax.swing.JPanel Resultado;
    private javax.swing.JButton butCalcular;
    private javax.swing.ButtonGroup buttonGroupRadioButton;
    private javax.swing.JComboBox<String> cboxNvlAtividade;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblGastoBasal;
    private javax.swing.JLabel lblGastoTotal;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNvlAtividade;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbutHomem;
    private javax.swing.JRadioButton rbutMulher;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JLabel txtGastoBasal;
    private javax.swing.JLabel txtGastoTotal;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables

    private void calculaGastoCal(double peso, double altura, int idade) {
        double calBasal = 0;

        //FAZ O CÁLCULO PARA HOMENS
        if (rbutHomem.isSelected()) {
            calBasal = 66 + (13.8 * peso) + (5 * altura) - (6.8 * idade);
        } //FAZ O CÁLCULO PARA MULHERES
        else if (rbutMulher.isSelected()) {
            calBasal = 655 + (9.6 * peso) + (1.9 * altura) - (4.7 * idade);
        }

        //ESCREVE NA TELA O GASTO BASAL
        setGastoBasal(calBasal);

        //CALCULA GASTO TOTAL
        calculaGastoTotal(calBasal);
    }

    private void calculaGastoTotal(double calBasal) {
        double calTotal = 0;

        switch (cboxNvlAtividade.getSelectedIndex()) {
            case 0 ->
                calTotal = calBasal * 1.2;
            case 1 ->
                calTotal = calBasal * 1.375;
            case 2 ->
                calTotal = calBasal * 1.55;
            case 3 ->
                calTotal = calBasal * 1.725;
            case 4 ->
                calTotal = calBasal * 1.9;
            default -> {
            }
        }

        //ESCREVE NA TELA O GASTO TOTAL
        setGastoTotal(calTotal);
    }

    private void setGastoBasal(Double calBasal) {
        //DEFINE A FORMATAÇÃO DO FLOAT
        DecimalFormat df = new DecimalFormat("####0.00");
        //SETA O TEXTO
        txtGastoBasal.setText(df.format(calBasal));
    }

    private void setGastoTotal(Double calTotal) {
        //DEFINE A FORMATAÇÃO DO FLOAT
        DecimalFormat df = new DecimalFormat("####0.00");
        //SETA O TEXTO
        txtGastoTotal.setText(df.format(calTotal));
    }
}
