/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividade2;

/**
 *
 * @author Claudemir
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMC = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Calculo = new javax.swing.JPanel();
        butCalcualr = new javax.swing.JButton();
        lblAltura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        Resultado = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        lblInterpr = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        txtInterpr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IMC");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblTitulo.setText("Cálculo de IMC:");

        Calculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        butCalcualr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        butCalcualr.setText("Calcular");
        butCalcualr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalcualrActionPerformed(evt);
            }
        });

        lblAltura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAltura.setText("Altura (m):");

        lblPeso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPeso.setText("Peso (kg):");

        javax.swing.GroupLayout CalculoLayout = new javax.swing.GroupLayout(Calculo);
        Calculo.setLayout(CalculoLayout);
        CalculoLayout.setHorizontalGroup(
            CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeso)
                    .addComponent(lblAltura))
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(butCalcualr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CalculoLayout.setVerticalGroup(
            CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(CalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butCalcualr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblResultado.setText("Resultado:");

        lblInterpr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblInterpr.setText("Interpretação:");

        txtResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtInterpr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout ResultadoLayout = new javax.swing.GroupLayout(Resultado);
        Resultado.setLayout(ResultadoLayout);
        ResultadoLayout.setHorizontalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(lblInterpr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInterpr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultadoLayout.createSequentialGroup()
                        .addComponent(lblResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ResultadoLayout.setVerticalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtResultado))
                .addGap(18, 18, 18)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterpr)
                    .addComponent(txtInterpr))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IMCLayout = new javax.swing.GroupLayout(IMC);
        IMC.setLayout(IMCLayout);
        IMCLayout.setHorizontalGroup(
            IMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IMCLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(IMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addComponent(Calculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IMCLayout.setVerticalGroup(
            IMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IMCLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTÃO DE CALCULAR
    private void butCalcualrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalcualrActionPerformed
        calculaImc(Float.parseFloat(txtPeso.getText()), Float.parseFloat(txtAltura.getText()));
    }//GEN-LAST:event_butCalcualrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calculo;
    private javax.swing.JPanel IMC;
    private javax.swing.JPanel Resultado;
    private javax.swing.JButton butCalcualr;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblInterpr;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JLabel txtInterpr;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables

    //CALCULA O IMC
    private void calculaImc(float peso, float altura) {
        float imc;
        // FAZ O CÁLCULO
        System.out.println("Peso: " + peso + " Altura: " + altura);
        imc = peso / (altura * altura);
        //CONVERTE FLOAT PARA STRING
        String res = Float.toString(imc);
        //ESCREVE NA TELA
        setResultado(res);
        interpretaIMC(imc);
    }

    //INTERPRETA O IMC
    private void interpretaIMC(float imc) {

        String mensagem = "";

        if (imc < 18.5) {

            mensagem = "Magreza";

        } else if (imc > 18.5 && imc <= 24.9) {

            mensagem = "Normal";

        } else if (imc > 25 && imc <= 29.9) {

            mensagem = "Sobrepeso";

        } else if (imc > 30 && imc <= 39.9) {

            mensagem = "Obesidade";

        } else if (imc >= 40) {

            mensagem = "Obesidade grave";

        }

        setInterpretacao(mensagem);
    }

    private void setResultado(String resultado) {
        txtResultado.setText(resultado);
    }

    private void setInterpretacao(String interpr) {
        txtInterpr.setText(interpr);
    }

}