package atividade2;

import java.text.DecimalFormat;

/**
 * @author Claudemir
 */
public class Recomendacoes extends javax.swing.JFrame {

    /**
     * Creates new form Recomendacoes
     */
    public Recomendacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recomendacoes = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Calcular = new javax.swing.JPanel();
        lblCalorias = new javax.swing.JLabel();
        txtCalorias = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Resultado = new javax.swing.JPanel();
        lblCarboidratos = new javax.swing.JLabel();
        lblProteina = new javax.swing.JLabel();
        lblGordura = new javax.swing.JLabel();
        txtCarboidratos = new javax.swing.JLabel();
        txtProteina = new javax.swing.JLabel();
        txtGordura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recomendações");

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setText("Recomendações");

        Calcular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCalorias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCalorias.setText("Calórias diárias (kcal):");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalcularLayout = new javax.swing.GroupLayout(Calcular);
        Calcular.setLayout(CalcularLayout);
        CalcularLayout.setHorizontalGroup(
            CalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcularLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCalorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        CalcularLayout.setVerticalGroup(
            CalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcularLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalorias)
                    .addComponent(txtCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCarboidratos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCarboidratos.setText("Carboidratos (50%):");

        lblProteina.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblProteina.setText("Proteína (25%):");

        lblGordura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblGordura.setText("Gordura (25%):");

        txtCarboidratos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtProteina.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtGordura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout ResultadoLayout = new javax.swing.GroupLayout(Resultado);
        Resultado.setLayout(ResultadoLayout);
        ResultadoLayout.setHorizontalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarboidratos)
                    .addComponent(lblProteina)
                    .addComponent(lblGordura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarboidratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProteina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGordura, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResultadoLayout.setVerticalGroup(
            ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarboidratos)
                    .addComponent(txtCarboidratos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProteina)
                    .addComponent(txtProteina))
                .addGap(35, 35, 35)
                .addGroup(ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGordura)
                    .addComponent(txtGordura))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout RecomendacoesLayout = new javax.swing.GroupLayout(Recomendacoes);
        Recomendacoes.setLayout(RecomendacoesLayout);
        RecomendacoesLayout.setHorizontalGroup(
            RecomendacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecomendacoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(RecomendacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        RecomendacoesLayout.setVerticalGroup(
            RecomendacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecomendacoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Recomendacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Recomendacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //RECEBE O VALOR DIGITADO
        calculaRecomend(Double.parseDouble(txtCalorias.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recomendacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calcular;
    private javax.swing.JPanel Recomendacoes;
    private javax.swing.JPanel Resultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCalorias;
    private javax.swing.JLabel lblCarboidratos;
    private javax.swing.JLabel lblGordura;
    private javax.swing.JLabel lblProteina;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCalorias;
    private javax.swing.JLabel txtCarboidratos;
    private javax.swing.JLabel txtGordura;
    private javax.swing.JLabel txtProteina;
    // End of variables declaration//GEN-END:variables

    private void calculaRecomend(double calorias) {
        double carb = 0, prot = 0, gord = 0;

        //REALIZA OS CALCULOS 
        carb = calorias * 0.5 / 4;
        prot = calorias * 0.25 / 4;
        gord = calorias * 0.25 / 9;

        //ESCREVE NA TELA
        setRecomend(carb, prot, gord);
    }

    private void setRecomend(Double carb, Double prot, Double gord) {
        //DEFINE A FORMATAÇÃO DO DOUBLE
        DecimalFormat df = new DecimalFormat("####0.00");
        //SETA O TEXTO
        txtCarboidratos.setText(df.format(carb) + " gramas");
        txtProteina.setText(df.format(prot) + " gramas");
        txtGordura.setText(df.format(gord) + " gramas");
    }

}
