package br.com.senac.financasjpa.gui;

/**
 * @author Claudemir
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadastroDespesa = new javax.swing.JMenuItem();
        miListagemDespesa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miCadastroReceita = new javax.swing.JMenuItem();
        miListagemReceita = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Despesa");

        miCadastroDespesa.setText("Cadastro");
        miCadastroDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroDespesaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroDespesa);

        miListagemDespesa.setText("Listagem");
        miListagemDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListagemDespesaActionPerformed(evt);
            }
        });
        jMenu1.add(miListagemDespesa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Receita");

        miCadastroReceita.setText("Cadastro");
        miCadastroReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroReceitaActionPerformed(evt);
            }
        });
        jMenu2.add(miCadastroReceita);

        miListagemReceita.setText("Listagem");
        miListagemReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListagemReceitaActionPerformed(evt);
            }
        });
        jMenu2.add(miListagemReceita);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroDespesaActionPerformed
        CadastroDespesa cadastroDespesa = new CadastroDespesa();
        cadastroDespesa.setVisible(true);
    }//GEN-LAST:event_miCadastroDespesaActionPerformed

    private void miListagemDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListagemDespesaActionPerformed
        ListagemDespesa listagemDespesa = new ListagemDespesa();
        listagemDespesa.setVisible(true);
    }//GEN-LAST:event_miListagemDespesaActionPerformed

    private void miCadastroReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroReceitaActionPerformed
        CadastroReceita cadastroReceita = new CadastroReceita();
        cadastroReceita.setVisible(true);
    }//GEN-LAST:event_miCadastroReceitaActionPerformed

    private void miListagemReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListagemReceitaActionPerformed
        ListagemReceita listagemReceita = new ListagemReceita();
        listagemReceita.setVisible(true);
    }//GEN-LAST:event_miListagemReceitaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCadastroDespesa;
    private javax.swing.JMenuItem miCadastroReceita;
    private javax.swing.JMenuItem miListagemDespesa;
    private javax.swing.JMenuItem miListagemReceita;
    // End of variables declaration//GEN-END:variables
}
